project_id = "umvhwbshppchbkgqhepk"

[functions.auth-start]
verify_jwt = false

[functions.revenuecat-webhook]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false
